require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CodeSamplesController do

  # This should return the minimal set of attributes required to create a valid
  # CodeSample. As you add validations to CodeSample, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CodeSamplesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all code_samples as @code_samples" do
      code_sample = CodeSample.create! valid_attributes
      get :index, {}, valid_session
      assigns(:code_samples).should eq([code_sample])
    end
  end

  describe "GET show" do
    it "assigns the requested code_sample as @code_sample" do
      code_sample = CodeSample.create! valid_attributes
      get :show, {:id => code_sample.to_param}, valid_session
      assigns(:code_sample).should eq(code_sample)
    end
  end

  describe "GET new" do
    it "assigns a new code_sample as @code_sample" do
      get :new, {}, valid_session
      assigns(:code_sample).should be_a_new(CodeSample)
    end
  end

  describe "GET edit" do
    it "assigns the requested code_sample as @code_sample" do
      code_sample = CodeSample.create! valid_attributes
      get :edit, {:id => code_sample.to_param}, valid_session
      assigns(:code_sample).should eq(code_sample)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CodeSample" do
        expect {
          post :create, {:code_sample => valid_attributes}, valid_session
        }.to change(CodeSample, :count).by(1)
      end

      it "assigns a newly created code_sample as @code_sample" do
        post :create, {:code_sample => valid_attributes}, valid_session
        assigns(:code_sample).should be_a(CodeSample)
        assigns(:code_sample).should be_persisted
      end

      it "redirects to the created code_sample" do
        post :create, {:code_sample => valid_attributes}, valid_session
        response.should redirect_to(CodeSample.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved code_sample as @code_sample" do
        # Trigger the behavior that occurs when invalid params are submitted
        CodeSample.any_instance.stub(:save).and_return(false)
        post :create, {:code_sample => { "title" => "invalid value" }}, valid_session
        assigns(:code_sample).should be_a_new(CodeSample)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CodeSample.any_instance.stub(:save).and_return(false)
        post :create, {:code_sample => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested code_sample" do
        code_sample = CodeSample.create! valid_attributes
        # Assuming there are no other code_samples in the database, this
        # specifies that the CodeSample created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CodeSample.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => code_sample.to_param, :code_sample => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested code_sample as @code_sample" do
        code_sample = CodeSample.create! valid_attributes
        put :update, {:id => code_sample.to_param, :code_sample => valid_attributes}, valid_session
        assigns(:code_sample).should eq(code_sample)
      end

      it "redirects to the code_sample" do
        code_sample = CodeSample.create! valid_attributes
        put :update, {:id => code_sample.to_param, :code_sample => valid_attributes}, valid_session
        response.should redirect_to(code_sample)
      end
    end

    describe "with invalid params" do
      it "assigns the code_sample as @code_sample" do
        code_sample = CodeSample.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CodeSample.any_instance.stub(:save).and_return(false)
        put :update, {:id => code_sample.to_param, :code_sample => { "title" => "invalid value" }}, valid_session
        assigns(:code_sample).should eq(code_sample)
      end

      it "re-renders the 'edit' template" do
        code_sample = CodeSample.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CodeSample.any_instance.stub(:save).and_return(false)
        put :update, {:id => code_sample.to_param, :code_sample => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested code_sample" do
      code_sample = CodeSample.create! valid_attributes
      expect {
        delete :destroy, {:id => code_sample.to_param}, valid_session
      }.to change(CodeSample, :count).by(-1)
    end

    it "redirects to the code_samples list" do
      code_sample = CodeSample.create! valid_attributes
      delete :destroy, {:id => code_sample.to_param}, valid_session
      response.should redirect_to(code_samples_url)
    end
  end

end
